= Configuration
:page-toclevels: 1

Pedestal primarily is configured via the xref:service-map.adoc[]; however, there are sub-systems within
Pedestal that can operate outside a service, or before a service map is used to create and start a server.

These sub-systems are:

- xref:dev-mode.adoc[]
- xref:logging.adoc[]
- xref:metrics.adoc[]
- Tracing


== Configuration Values

Configuration values are one of the following types:

- boolean
- keyword
- function

For functions config types, the value is converted to a fully qualified symbol and that is resolved
to a function.

== Configuration Order

Pedestal uses late binding to configure these values, so that it is possible to customize Pedestal's behavior to
the operating environment: anything from local developer to final production.

Pedestal will search a series of sources for a value that identifies the var; these are in a specific order,
with an eye towards making it possible to override the value at runtime for testing or production, as that is often
a need for these subsystems.

- JVM system property name
- Environment Variable
- Entry in the `pedestal-test-config.edn` resource
- Entry in the `pedestal-config.edn` resource
- A hard-coded default, or nil

The intent is that a Pedestal application will typically include a `pedestal-config.edn` on the classpath (packaged with
the application's sources or compiled classes, typically stored in `resources`); the `pedestal-test-config.edn` will
only be on the classpath during local testing (typically, stored in `test-resources`).

When necessary, these values can be overrridden when deployed to a staging or production deployment using
environment variables or JVM system properties.

If you only occasionally need to set a configuration value, this can be done from the
command line by using the `-J` switch:

    clj -J-Dio.pedestal.dev-mode=true ...

Alternately, you can update your `deps.edn` file, associating a JVM option with an alias:

[source]
----
   ...
   :aliases
     {:dev-mode
       {:jvm-opts ["-Dio.pedestal.dev-mode=true"]}
   ...
----

You can then reference the alias when starting a REPL session:

    clj -A:dev-mode ...

== EDN Configuration Files

The contents of `pedestal-config.edn` (and `pedestal-test-config.edn`) are EDN maps.

The keys are the JVM property converted to a keyword (for example, :io.pedestal.log.overrideLogger).

For values that are function types, the config value can be either a qualified symbol, or a string that is converted to a qualified symbol.

For values that are boolean, the config value may be a boolean or a string.

== Configuration Keys

Once a symbol is obtained from a configuration source, it is resolved to a Clojure Var.  Each use
of configuration has its own interpretation of the Var.

The following section list the current configuration values; each heading identifies the JVM system property,
then the equivalent environment variable.

[#dev-mode]
=== io.pedestal.dev-mode / PEDESTAL_DEV_MODE

- type: boolean

Enables xref:dev-mode.adoc[].

=== io.pedestal.log.overrideLogger / PEDESTAL_LOGGER

- type: function

Used to create an api:LoggerSource[ns=io.pedestal.log] instance from a logger name;
  If not specified, then `org.slf4j.LoggerFactory.getLogger(java.lang.String)` is used.

=== io.pedestal.log.formatter / PEDESTAL_LOG_FORMATTER

- type: function

A function used to format a logged event map to a string prior to being passed to the LoggerSource.
When not specified, clj:pr-str[] is used.

[#disable-handler-names]
=== io.pedestal.interceptor.disable-default-handler-names / PEDESTAL_DISABLE_DEFAULT_HANDLER_NAMES


- type: boolean
- default: false

If true, then Pedestal will not automatically convert
xref:interceptors.adoc#handler[handler function] class names to an interceptor name (the interceptor
will be anonymous instead).

[#suppress-deprecation-warnings]
=== io.pedestal.suppress-deprecation-warnings / PEDESTAL_SUPPRESS_DEPRECATION_WARNINGS

- type: boolean

- default: false

If true, then deprecation warnings are suppressed.

=== io.pedestal.telemetry.metric-source / PEDESTAL_METRICS_SOURCE

- type: function
- default: api:metric-source[ns=io.pedestal.telemetry.otel-global-init]

A function that returns an instance of api:MetricSource[ns=io.pedestal.metrics.spi] used to create metrics used by
Pedestal or applications.

The default is to get the value from
`io.opentelemetry.api.GlobalOpenTelemetry.getMeter(java.lang.String)`.

[#metric-value-type]
=== io.pedestal.telemetry.metric-value-type / PEDESTAL_METRICS_VALUE_TYPE

- type: keyword (:long or :double)
- default: :long

The kind of values provided to the api:MetricSource[ns=io.pedestal.metrics.spi].

=== io.pedestal.telemetry.tracing-source/ PEDESTAL_TRACING_SOURCE

- type: function
- default: api:tracing-source[ns=io.pedestal.telemetry.otel-global-init]

A function that returns an instance of
api:TracingSource[ns=io.pedestal.tracing.spi], used to emit tracing events.

The default, gets its value
from `io.opentelemetry.api.GlobalOpenTelemetry.getTracer(java.lang.String)`.

