= Pedestal Connector
:reftext: connector
:navtitle: Connector

A Pedestal application always works in the context of a _network connector_ such as
xref:jetty.adoc[]; the network connector is responsible for the low-level HTTP/HTTPs networking,
including support for WebSockets and server-sent events.

TIP: Pedestal connectors were added in version 0.8.0 and are the _preferred_ way of setting up your application.

Once a request has been received, it is passed through
an interceptor chain to be processed using the
xref:interceptors.adoc[] pipeline.

A Pedestal connector is created from a xref:connector-map.adoc[]; the Pedestal connector
manages the lifecycle of the network connector, and transforms from the network connector's
APIs to Pedestal's.

The namespaces api:*[ns=io.pedestal.connector] and api:*[ns=io.pedestal.connector.dev] provide functions to create
and configure the connector map.

The connector concept was added in Pedestal 0.8; a connector does not require a servlet or anything from the
Servlet API; the xref:http-kit.adoc[Http-Kit connector] is an example that provides HTTP functionality without
the Servlet API.

By contrast, the older Jetty support can run as a service (that is, in terms of the Servlet API) _or_ as a connector.

== Embedded

Pedestal applications are primarily run in _embedded_ mode, where the network connector is a library that is part of the runtime classpath.

The xref:service-map.adoc[] is passed to a connector factory function.

Pedestal connectors implement the api:PedestalConnector[ns=io.pedestal.service.protocols] protocol.  When started,
the Pedestal connector will create, configure, and start the network connector.

Once started, the network connector will receive incoming
requests and pass those along to Pedestal for actual processing.

== WAR (Web Application Archive)

The alternate setup for a Pedestal application is a WAR file - a packaged version of an application, its code and libraries, configuration, and public resources - that runs inside a standalone servlet connector.
WAR deployments have a different lifecycle, as the network connector (such as xref:jetty.adoc[]) is its own
running process, that unpacks and loads the contents of the WAR file.  This means that there isn't a Pedestal connector,
just the xref:servlet-interceptor.adoc[].

This all requires some careful setup, including omitting certain dependencies from the classpath.

WARNING: More discussion of WAR deployment is forthcoming.
