= Default Interceptors

Some of the default interceptors are conditional. Pedestal adds them
when other parts of the service map indicate a need for an
interceptor. These will be noted below.

These are presented in the order that they appear in the interceptor
vector. That means their :enter functions will be called in the order
they appear in this document, and their :leave functions are called
in reverse order.

The following identifies the interceptor by their var or function, in the order they are
added by `default-interceptors`.

=== api:request-tracing-interceptor[ns=io.pedestal.http.tracing]

Always added, unless the :io.pedestal.http/tracing options is set to nil.

=== api:log-request[]

Always added. Logs each request at `info` level. See xref:logging.adoc[]
to configure loggers and logging levels.

=== api:allow-origin[]

Added when the service map has a value for :io.pedestal.http/allowed-origins.

=== api:not-found[]

Always added. However, if the service map includes a value for
:io.pedestal.http/not-found-interceptor, then that interceptor will
be used in this position instead of the built-in.

=== api:session[ns=io.pedestal.http.ring-middlewares]

Added when the service map has a value for
:io.pedestal.http/enable-session or :io.pedestal.http/enable-csrf.

=== api:anti-forgery[ns=io.pedestal.http.csrf]

Added when the service map includes a value for :io.pedestal.http/enable-csrf.

=== api:content-type[ns=io.pedestal.http.ring-middlewares]

Always added.

=== api:query-params[ns=io.pedestal.http.route]

Always added.

=== api:method-param[ns=io.pedestal.http.route]

Always added.

=== api:resource[ns=io.pedestal.http.ring-middlewares]

Added when the service map has a value for :io.pedestal.http/resource-path.

=== api:file[ns=io.pedestal.http.ring-middlewares]

Added when the service map has a value for :io.pedestal.http/file-path.

=== api:secure-headers[ns=io.pedestal.http.secure-headers]

Added when the service map has a non-nil value for
:io.pedestal.http/secure-headers or when the service map does not
include the key :io.pedestal.http/secure-headers at all.

=== api:router[ns=io.pedestal.http.route]

Always added.

=== api:path-params-decoder[ns=io.pedestal.http.route]

Added unless :io.pedestal.http/path-params-decoder is not is set to nil.

