= Pedestal Libraries

Pedestal is composed of multiple libraries, and many of these can be used outside of a Pedestal application.

[graphviz]
----
digraph G {
  "pedestal.common" ->  "org.clj-commons/pretty";
  "pedestal.telemetry" -> "pedestal.common";
  "pedestal.log" -> "pedestal.common";
  "pedestal.telemetry" -> "Open Telemetry";
  "pedestal.interceptor" -> "pedestal.common", "pedestal.log", "org.clojure/core.async", "org.clj-commons/pretty;
  "pedestal.error" -> "pedestal.interceptor", "org.clojure/core.match";
  "pedestal.route" -> "pedestal.log", "pedestal.interceptor", "pedestal.common", "org.clojure/core.async", "org.clj-commons/pretty";

  "pedestal.service" -> "pedestal.telemetry", "pedestal.intereptor", "pedestal.route",
    "org.clojure/core.async", "ring/ring.core";
    "pedestal.servlet" -> "pedestal.service", "Jakarta Servlet APIs";
    "pedestal.jetty" -> "pedestal.servlet", "jetty-service, ...";
    "pedestal.http-kit" -> "pedestal.service", "http-kit/http-kit";


}
----

[%header,cols=2]
.Pedestal Libraries Summary
|===
| Library Name
| Description

| pedestal.common
| Common functionality and internal utilities.

| pedestal.telemetry
| Wrapper around https://opentelemetry.io/[Open Telemetry] for generating application metrics and tracing.

| pedestal.log
| Wrapper around https://www.slf4j.org/[Simple Logging Facade for Java]

| pedestal.interceptor
| Asynchronous xref:interceptors.adoc[interceptor pipeline]

| pedestal.error
| Simple error catching for interceptors

| pedestal.route
| HTTP request xref:routing-quick-reference.adoc[routing]

| pedestal.service
| Connector-agnostic HTTP service support

| pedestal.servlet
| Servlet-API specific

| pedestal.jetty
| xref:jetty.adoc[] connector

| pedestal.http-kit
| xref:http-kit.adoc[] connector

|===

== Artifact Coordinates

Pedestal libraries are uploaded to the https://clojars.org/[Clojars] repository; files in such a repository
are called _artifacts_.

All pedestal libraries are in the `io.pedestal` group.

For https://leiningen.org/[Leiningen], add this vector to
the :dependencies list inside your `project.clj`:

[subs="attributes"]
----
    [io.pedestal/pedestal.jetty "{libs_version}"]
----

You will adjust the library name as necessary.

For Clojure Deps, add this key and value to the :deps map inside your `deps.edn`:

[subs="attributes"]
----
 io.pedestal/pedestal.jetty {:mvn/version "{libs_version}"}
----

== Git Artifact Coordinates

Pedestal is built using Clojure Deps; this means that it is possible to
get access to bleeding-edge versions of the libraries
https://clojure.org/reference/deps_and_cli#_dependencies[directly from the GitHub repository].

----
  io.pedestal/pedestal.jetty {:git/url "https://github.com/pedestal/pedestal.git"
                              :git/sha "a0b6a0f7e57710ba6b9f0aa3a62dd1f68e278f43"
                              :deps/root "jetty"}
----

All Pedestal libraries are in the same repository, :deps/root is used to select
the sub-directory containing the library's code (this matches the library name,
without the `pedestal.` prefix).

[WARNING]
====
:git/url's are not transitive; when the library you select has dependencies
on other Pedestal libraries, those will be accessed as :mvn/version dependencies.
You may need to provide additional dependencies to bring in multiple
Pedestal libraries.

For example, if you are verifying a bug fix that was split between pedestal.route and
pedestal.service, you should introduce dependencies on both libraries; otherwise
you may only get half of the bug fix.
====


