= Routing Changes in 0.8
:default_api_ns: io.pedestal.http.route

A significant part of the 0.8 development cycle has been to improve and upgrade routers.
In most cases, the new logic is a drop-in replacement for the old.

If you are upgrading from 0.7 or earlier, and _you implement your own routers or routing specifications_,
you will need to be aware of these changes. This should not affect the vast majority of Pedestal applications.

[WARNING]
====
The naming of routing-related protocols and methods of those protocols is quite confusing; it will take some
real work over much time to straighten that out. Focus on what the protocols _do_ rather than how
they are _named_.
====

In addition, the xref:sawtooth-router.adoc[] is now the default router; the others are kept primarily for
backwards compatibility.

== Table Routes

It is now possible to set a list of prefix interceptors that apply to all routes defined by a call to
api:table-routes[ns=io.pedestal.http.route.definition.table].

It is now allowed to define additional key/value pairs at the end of the route (after :route-name and/or :constraints).
These routes will be available at runtime after routing, allowing for generic interceptors that act based on values
stored in the route map.

== Private Functions

Many of the namespaces used in routing had internal functions not marked as private; these have
been made private.

== New: Routing Fragment vs. Routing Table

Previously, it was assumed that there was a single specification for all routes; in trivial examples
this might be a set (which, via the RouteSpecification protocol) is interpreted as a
call to api:table-routes[ns=io.pedestal.http.route.definition.table].

Other applications might invoke `table/table-routes` directly.

In either case, this value is provided
to api:with-routes[ns=io.pedestal.connector], or as the ::http/routes key of the
xref:service-map.adoc[].

TIP: Pedestal 0.7 only supported a single set of routes; but `with-routes` supports any number
of routes, which are merged together.

The return type of `table-routes/routes`, and the other built-in route definitions
(api:terse-routes[ns=io.pedestal.http.route.definition.terse] and
api:expand-verbose-routes[ns=io.pedestal.http.route.definition.verbose]) have been changed;
previously they returned a seq of route maps; they now return a
api:RoutingFragment[ns=io.pedestal.http.route.types] (essentially, a wrapper around a seq
of route maps).

Likewise, the api:routes-from[] macro (on which `with-routes` builds) now accepts a variable number of expressions.

== ExpandableRoutes

The api:ExpandableRoutes[] protocol is now used to convert an arbitrary data structure to
a `RoutingFragment` (not a seq of expanded routes); these fragments are then combined,
by api:expand-routes[], into the full routing table.

Previously, `expand-routes` only accepted a single value; it now accepts one or more RoutingFragments.

== RouterSpecification Protocol

The RouterSpecification protocol was used to choose a different strategy based on whether the routing table
was an actual value, or a function that returns a value; the protocol has been removed
as there were only ever two implementations.

== Router Protocol

The Router protocol, and the containing io.pedestal.http.route.router namespace, have been removed;
instead, each router contructor simply returns a router function.

The contract has changed slightly; on a successful route, the router function returns a tuple of
two values:

* The matching route
* The map of path parameter values (extracted from the request's path)
