= Service Map
:reftext: service map
:navtitle: Service Map
:default_api_ns: io.pedestal.service

Pedestal provides functions to create a xref:connector.adoc[].

The service map contains general information that any Pedestal connector will need to create a network connector.
This is supplemented by a connector-specific configuration map.

== Service Map Keys

An initial service map can be created by api:default-service-map[].

[cols="s,d,d", options="header", grid="rows"]
|===
| Key |  Type | Description

| :port | Number | Port for the network connector to receive connections on
| :host | String | Hostname to listen on, defaults to "localhost"
| :interceptors | Vector | Interceptor to used when processing requests.
| :initial-context | Map | Initial context that will be used when executing the interceptor chain
| :join? | Boolean | If true (the default is false) then the current thread will block when the connector is started.
|===

The created Pedestal connector will often prefix the supplied interceptors with ones specific to the connector.

TIP: Supplying an :initial-context is a way to provide useful data, functions, or components to all interceptors
and handlers.

== Default interceptors

The api:with-default-interceptors[] function is used to add interceptors to the service map for much
common functionality.  It is passed the service map and an additional configuration map and will
add interceptors for the following functionality:

* Request tracing
* Request logging
* Allowed origins
* Session support
* Cross site request forgery detection
* Default content type for responses
* Parsing of query parameters
* Secure headers (adds a few headers to improve security)

[WARNING]
====
`with-default-interceptors` is useful, but limited. It doesn't let you fully configure many of the interceptors
it adds, and it may add interceptors you do not need.
It is intended as _scaffolding_: useful only at the outset of a new project, but should be
removed and replaced with application specific setup once development is fully underway.
====

If the value for ::http/secure-headers is present, it may contain
keys and string values for the security headers. Any other keys will be ignored.

== Files and Resources

The api:with-file-access[] and api:with-resource-access[] functions add interceptors that will expose
file system or class path resources to the client; this is an alternative to xref:resources.adoc[exposing
files and resources via routes].

== Routing

The api:with-routing[] macro is used to add a router and routes to your service.
It is a macro because it sets up a REPL-friendly
workflow (when in xref:dev-mode.adoc[development mode]).

== Creating the Pedestal connector

The service map is passed to a Pedestal connector factory function, along with a map of configuration
specific to the Pedestal connector, and returns a
api:PedestalConnector[ns=io.pedestal.service.protocols] object, which can be started with api:start![].

Factory functions:

- api:create-connector[ns=io.pedestal.http.jetty] (Jetty)
- api:create-connector[ns=io.pedestal.http.http-kit] (Http-Kit)

== Spec Validation

The service map can grow quite complex, with options controlling everything from routing, to
security, to container-specific options.

The service map may be validated via {clojure_spec}; this involves loading the
appropriate xref:specs.adoc[spec namespaces] and using
Clojure's built-in link:https://clojure.org/guides/spec#_instrumentation_and_testing[instrumention and testing support].
