= Websockets
:default_api_ns: io.pedestal.websocket

link:https://en.wikipedia.org/wiki/WebSocket[WebSockets] are an asynchronous and bidirectional connection between
a client and a server.  Once a Websocket connection is established, either
party may send messages to the other party - this unleashes truly unbounded possibilities for creating dynamic, real-time, and asynchronous applications.

== WebSocket Lifecycle

A WebSocket connection starts with the client (the web browser) sending an HTTP or HTTPS request; this request
includes a special header to indicate that it is intended to upgrade the request to a WebSocket connection; it is
always a GET request.

In the handling of this kind of request, there's a point where the request is
https://javadoc.io/static/jakarta.websocket/jakarta.websocket-api/2.2.0/jakarta/websocket/server/ServerContainer.html#upgradeHttpToWebSocket(java.lang.Object,java.lang.Object,jakarta.websocket.server.ServerEndpointConfig,java.util.Map)[upgraded to a WebSocket connection].
There is _no_ response to this request. Instead, both the client and the server may begin sending and receiving text
and binary messages until the connection is closed by either party.

== WebSockets in Java

In Java, WebSocket endpoints are POJO objects with
a https://javadoc.io/static/jakarta.websocket/jakarta.websocket-client-api/2.2.0/jakarta/websocket/ClientEndpoint.html[@ClientEndpoint]
class annotation.

Such endpoints will annotate specific methods to mark them as callbacks for asynchronous events.
For example, to handle initial setup when a connection is first opened, the
https://javadoc.io/static/jakarta.websocket/jakarta.websocket-client-api/2.2.0/jakarta/websocket/OnOpen.html[@OnOpen]
annotation can be applied.

Other annotations cover receiving text or binary messages.

== WebSockets in Pedestal

Under Pedestal, a WebSocket request is routed like any other request, but the final interceptor
must invoke
api:upgrade-request-to-websocket[]
instead of attaching a response.
In many cases, the final interceptor is created via api:websocket-upgrade[].

The behavior of the endpoint is defined in terms of a _websocket map_ which provides configuration for the WebSocket,
as well as callbacks for specific events in the WebSocket lifecyle.

.Callbacks
|===
| Key | Signature | Description

| :on-open
| (Session, EndpointConfig) -> Object
| Invoked when the client first opens a connection.
  The returned value is retained and passed as the first argument of the remaining callbacks.

| :on-close
| (Object, Session, CloseReason) -> nil
| Invoked when the socket is closed, allowing any resources to be freed.

| :on-error
| (Object, Session, Throwable) -> nil
| Passed any unexpected exception.

| :on-text
| (Object, String) -> nil
| Passed a text message from the client, as a single String.

| :on-binary
| (Object, ByteBuffer) -> nil
| Passed a binary message, as a single ByteBuffer.

| :configure
| (ServerEndpointConfig$Builder) -> nil

| Allows additional configuration using an instance of
https://javadoc.io/static/jakarta.websocket/jakarta.websocket-api/2.2.0/jakarta/websocket/ClientEndpointConfig.Builder.html[ClientEndpointConfig.Builder].

  This configuration occurs before the request is upgraded to a connection, and provides access to other configuration
  options, such as encoders and decoders, that are not yet exposed by Pedestal's API.

|===

.Configuration
|===
| Key | Type | Description

| :subprotocols
| vector of String
| Optional, specifies sub-protocols for the websocket connection

| :idle-timeout-ms
| long
| Sets the max idle timeout for the websocket to a fixed value.
|===

Essentially, the :on-open callback is invoked when the client initiates the connection.

It is intended that, when the client connects, some form of server-side process will be initiated
capable of sending messages to the client asynchronously.
It is the responsibility of the :on-open callback to create such a process.
One common option is to use the api:on-open-start-ws-connection[] function to create the callback, or
construct the :on-open callback around the api:start-ws-connection[] function.

The :on-text and :on-binary callbacks are invoked when a text or binary message from the client
is received.


== Upgrading from Pedestal 0.7





Websocket requests are not routed the way HTTP requests are; instead, the mapping from incoming requests
to Websocket handlers is defined in the xref:service-map.adoc[].

In the service map, the :io.pedestal.http/websockets key
maps string routes to endpoint maps.
