FROM openjdk:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/override-logging-0.0.1-SNAPSHOT-standalone.jar /override-logging/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/override-logging/app.jar"]
