FROM java:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/server-sent-events-0.0.1-SNAPSHOT-standalone.jar /server-sent-events/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/server-sent-events/app.jar"]
