#!/bin/sh

# Copyright 2013 Relevance, Inc.

# The use and distribution terms for this software are covered by the
# Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0)
# which can be found in the file epl-v10.html at the root of this distribution.
#
# By using this software in any fashion, you are agreeing to be bound by
# the terms of this license.
#
# You must not remove this notice, or any other, from this software.

# Test ClojureScript on V8

rm -rf out
mkdir -p out
mkdir -p test/cljs/io/pedestal/app/data

possible=1
ran=0

# copy shared files
cp src/io/pedestal/app/data/change.clj test/cljs/io/pedestal/app/data/change.cljs

if [ "$CLOJURESCRIPT_HOME" = "" ]; then
    echo "CLOJURESCRIPT_HOME not set"
else

    CLJSC_CP=''
    for next in lib/*: src/clj: src/cljs: test/cljs; do
        CLJSC_CP="${CLJSC_CP}${CLOJURESCRIPT_HOME}/${next}"
    done
    for next in src: test/cljs; do
        CLJSC_CP="${CLJSC_CP}:${next}"
    done

    echo "Compiling with simple optimizations..."
    java -server -cp "$CLJSC_CP" clojure.main "$CLOJURESCRIPT_HOME/bin/cljsc.clj" test "{:optimizations :simple}" >out/simple-test.js
    echo "Compiling with advanced optimizations..."
    java -server -cp "$CLJSC_CP" clojure.main "$CLOJURESCRIPT_HOME/bin/cljsc.clj" test "{:optimizations :advanced}" >out/advanced-test.js
    
    if [ "$V8_HOME" = "" ]; then
        echo "V8_HOME not set, skipping V8 tests"
    else
        echo "Testing simple compilation with V8"
        "${V8_HOME}/d8" out/simple-test.js
        echo "Testing advanced compilation with V8"
        "${V8_HOME}/d8" out/advanced-test.js
        ran=$[ran+1]
    fi
    
    echo "Tested with $ran out of $possible possible js targets"

fi

# cleanup
rm test/cljs/io/pedestal/app/data/change.cljs
