= Server Sent Events

== Welcome

Server-sent events (SSE) make it possible to stream events to a client application.
They are appropriate when you only need a unidirectional flow of events from the
server to the client (if you need a bidirectional connection, then WebSockets are
a better choice).

== What You Will Learn

After reading this guide, you will be able to:

- Configure Pedestal to accept SSE connections.
- Send events from Pedestal over the connection using {core_async}.
- Connect to the server-sent event stream from a JavaScript client.

== Guide Assumptions

This guide is for intermediate users who have worked through some
sample applications or the first few xref:hello-world.adoc[]
guides. In particular, you should know how to run a build, start a
REPL, and start and stop your server.

You do not need to know any other Clojure web frameworks, but if you
do, you may find some of the comparisons useful. If not, that's OK --
just skip those sections.

== Getting Help if You're Stuck

include::partial$getting-help.adoc[]

== Server Sent Events Overview

In typical client/server interactions, the client, usually a web browser, sends a single request to the server,
and the server responds with a single response.

With SSEs, this is a bit different.  The client still sends a single request, and receives a single response,
but it doesn't get the response all at once.  The response body "stays open", and the server can keep appending
more content to it.

With SSEs, the response content type is `text/event-stream`.  This event stream consists of
multiple "events", short text-based messages.

== Where We Are Going

We'll be creating a new Pedestal service project, adding a simple route to stream a counter using server-sent events, and adding a simple HTML page that uses a JavaScript https://developer.mozilla.org/en-US/docs/Web/API/EventSource[EventSource] to open a connection to the stream.

== Before We Begin

We'll use the xref:embedded-template.adoc[] to create the basics of our project, then add and modify what we need.

== Generate Our New Project

----
$ clojure -Tnew create :template \
  io.github.pedestal/pedestal%embedded%io.pedestal/embedded#0.8.0-beta-1 \
  :name org.example/sse
Resolving io.github.pedestal/pedestal as a git dependency at 0.8.0-beta-1
Creating project from io.pedestal/embedded in sse
$ cd sse
----

This will create namespaces `org.example.sse.connector`, `org.example.sse.main`, and so forth, along with
Logback configuration files  `resources/logback.xml` and `test-resources/logback-test.xml`.

== Wrapping Up

We've covered a minimal setup for server-sent event configuration and usage and
demonstrated how to receive events from JavaScript.

This guide was based on the examples in the 
link:{repo_root}/samples/tree/master/server-sent-events[server-sent-event sample project]
and the
xref:reference:server-sent-events.adoc[Server-Sent Events Reference].

