version: 0.1

phases:
  install:
    commands:
      - cd ~; wget https://raw.github.com/technomancy/leiningen/stable/bin/lein; chmod +x lein; mv lein /bin
      - LEIN_ROOT=true lein
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - LEIN_ROOT=true lein uberjar
      - mv target/pedestal-lambda-0.0.1-SNAPSHOT-standalone.jar .
      - jar xf pedestal-lambda-0.0.1-SNAPSHOT-standalone.jar
      - rm -rf target src buildspec.yml project.clj pom.xml pedestal-lambda-0.0.1-SNAPSHOT-standalone.jar.jar
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.json
artifacts:
  files:
    - template-export.json
